Issue 128
AustinGrey/cmput404-group-project pull request #130
Opened 2020-03-11 16:53 UTC by XuechunHou

#128

2020-03-12 04:47 UTC, AustinGrey requested changes

2020-03-12 04:47 UTC, AustinGrey commented on web_server/authors/views.py
> +        return HttpResponse("Post body missing fields: display_name", status=422)
This is a lot of code duplication. Is there no way to simplify this?

2020-03-13 18:06 UTC, XuechunHou commented
changes made. removed duplicate code.

2020-03-13 18:34 UTC, AustinGrey approved these changes
Great solution, much cleaner. Could you please again check that you are not auto

2020-03-13 18:34 UTC, AustinGrey commented on web_server/authors/views.py
> +        new_post.author = request.user         # the authenticated user
This is an example of an area of the code you keep changing that is reducing readability. It's not a huge issue so I'm going to approve and merge, but please prevent your IDE from automatically changing the code others keep formatting to keep readable.

2020-03-13 18:35 UTC, merged