First Version of User Auth System
AustinGrey/cmput404-group-project pull request #54
Opened 2020-02-10 03:35 UTC by XuechunHou

Features Implemented:

1. Sign up
    - [X]  form field validation 

     - [X] basic UI implementation
2. Log in
     - [X] form field validation
     -  [X] basic UI implementation
     - [X] session cookie: a single login session last for 10 hrs 
3. Also created an ugly user profile page

2020-02-10 18:50 UTC, AustinGrey approved these changes
Please see my comment about crispy-forms

2020-02-10 18:50 UTC, AustinGrey commented on web_server/social_distribution/settings.py
> +    'crispy_forms'
Crispy forms seems to be library you are using? Why? Do we have a place to document this so if the front end people try using something else we dont conflict?

2020-02-10 19:02 UTC, AustinGrey requested changes
Actually I just tried to run this locally and couldn't because I didn't have crispy-forms. Do you mind adding a requirement.txt so that everyone can have the same modules installed in their venv? You should be able to make one from your venv by running pip --freeze

2020-02-11 00:51 UTC, XuechunHou commented
`Django==2.2.9
django-clear-cache==0.3
**django-crispy-forms==1.8.1**
pytz==2019.3
sqlparse==0.3.0
`
django-crispy-forms is the only packages I donwloaded, it's a form styling framework..
pip install --upgrade django-crispy-forms

2020-02-11 16:01 UTC, AustinGrey commented
Great, that's simple then. Please commit the requirements.txt file and push so that we have the dependency documented. We won't be able to use heroku without the dependencies listed in the requirements.txt

2020-02-11 17:59 UTC, AustinGrey commented
Please see slack - it turns out everyone has been using different versions of Django. We should standardize. You have 2.2, 2 other team members were on 2.1, I had 3. Do you have any thoughts on that?

2020-02-11 19:54 UTC, AustinGrey commented
As per slack, 2.2 is now the chosen version of Django. Thus this PR is in line and can continue.

2020-02-11 19:54 UTC, merged